### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by schindld** [Pangoraw/font-preview#1]
Love the package, once I made a small change to get it working in Windows. The problem is that paths on Windows have backslashes, which need to be escaped or replaced with forward slashes before using them for a font's url.

The fix I found was to add this to the start of your initialize(filePath) function in font-preview-view.js:

    filePath = path.resolve(filePath).replace(/\\/g, '/');
    if (filePath[0] !== '/') {
      filePath = '/' + filePath;
    }
    filePath = encodeURI('file://' + filePath);
-source: http://stackoverflow.com/a/28214523/257489

I'm not sure if the last line (prepending 'file://') breaks it in Linux. If it does, then wrap it in a test for windows, like `/^win/.test(process.platform)`

**Comment by Pangoraw** [comment]
Thanks for reporting the bug !

I patched it, and it should now work on windows as well.
