### ISSUE TITLE
Any instuctions of this plugin?

### ISSUE THREAD

**Issue by rediffusion** [Pangoraw/font-preview#2]
Hello dear! ✋
I don't understand how to use it, any docs are there?
I want to open and watch .woff file witch has [icons](https://dropmefiles.com/jaLxz) inside.

Cheers!  😀

**Comment by Pangoraw** [comment]
Hello,
I don't use Atom anymore and thus I don't really have time to invest in maintaining this package.
You are welcome to create your own fork or use any alternative.
Thanks :+1:
